services:
  # inbox-web:
    # build:
      # context: .
      # dockerfile: apps/web/dockerfile.staging.yaml
    # ports:
      # - "3000:3000"
    # env_file:
      # -  ./apps/web/.env
    # networks:
      # - inbox 
    # deploy:
      # resources:
        # limits:
          # cpus: '1.5'
          # memory: 2G     
  http-server:
    container_name: http-server
    build:
      context: .
      dockerfile: apps/http-server/dockerfile.staging.yaml
    ports:
      - "3002:3002"
    env_file:
      -  ./apps/http-server/.env 

    networks:
      - inbox
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1G     
  publisher-publish-mail-from-imap:
      container_name: publisher-publish-mail-from-imap
      build:
        context: .
        dockerfile: apps/publisher-publish-mail-from-imap/dockerfile.staging.yaml
      ports:
        - "3009:3009"
      env_file:
        -  ./apps/publisher-publish-mail-from-imap/.env
      networks:
        - inbox
      deploy:
        resources:
          limits:
            cpus: '0.25'
            memory: 1G
      depends_on:
        - rabbitmq
        - elasticsearch    
        - http-server                                                    
  label-assigner:
    container_name: label-assigner
    build:
      context: .
      dockerfile: apps/label-assigner/dockerfile.staging.yaml
    ports:
      - "3007:3007"
    env_file:
      -  ./apps/label-assigner/.env
    networks:
      - inbox
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 2G
    depends_on:
      - rabbitmq
      - elasticsearch               
  worker:
    container_name: worker
    build:
      context: .
      dockerfile: apps/worker/dockerfile.staging.yaml
    ports:
      - "3008:3008"
    env_file:
      -  ./apps/worker/.env
    networks:
      - inbox
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 2G
    depends_on:
      - rabbitmq
      - elasticsearch
  consumer-push2storage:
    container_name: consumer-push2storage
    build:
      context: .
      dockerfile: apps/consumer-push2storage/dockerfile.staging.yaml
    ports:
      - "3010:3010"
    env_file:
      -  ./apps/consumer-push2storage/.env
    networks:
      - inbox
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1G
    depends_on:
      - rabbitmq
      - elasticsearch
  # redis:
    # image: "redis:latest"
    # environment:
      # REDIS_PASSWORD: inbox_password
      # REDIS_USERNAME: inbox_user
    # ports:
      # - "6379:6379"
    # volumes:
      # - redis-data:/data
    # networks:
      # - inbox 
    # deploy:
      # resources:
        # limits:
          # cpus: '0.5'
          # memory: 700M
  # postgres-db:
    # image: "postgres:latest"
    # environment:
      # POSTGRES_USER: inbox_user
      # POSTGRES_PASSWORD: inbox_password
      # POSTGRES_DB: inbox_db
    # volumes:
      # - postgres-data:/var/lib/postgresql/data
    # ports:
      # - "5432:5432"
    # networks:
      # - inbox
    # deploy:
      # resources:
        # limits:
          # cpus: '0.4'
          # memory: 700M    
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: inbox_user
      RABBITMQ_DEFAULT_PASS: inbox_password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - inbox
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G   

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2 
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      # - bootstrap.memory_lock=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx2g"
      - "logger.level=DEBUG"
      - "logger.org.elasticsearch=DEBUG"
    volumes:
      - es-data:/usr/share/elasticsearch/data 
      - ./logs:/usr/share/elasticsearch/logs 
    # ulimits:
      # memlock:
        # soft: -1
        # hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - inbox
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '2G'           
networks:
  inbox:
    driver: bridge          
volumes:    
  es-data:
  rabbitmq-data:
