FROM node:20 as base
RUN npm install -g pnpm turbo

FROM base AS prunner
ARG APP=label-assigner
WORKDIR /app
COPY . .
RUN turbo prune --scope=$APP --docker
FROM base AS installer
WORKDIR /app
ARG APP=label-assigner
COPY --from=prunner /app/out/json/ .
COPY --from=prunner /app/out/full/ .
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/${APP}/package.json ./apps/${APP}/package.json
RUN pnpm install --filter ${APP}


FROM base AS builder
ARG APP=label-assigner
WORKDIR /app
COPY --from=installer /app ./
WORKDIR /app/apps/${APP}

RUN pnpm --filter=${APP}... run build
RUN pnpm --filter=${APP} deploy /app/outdir --prod

FROM node:20 as runner
ARG APP=label-assigner
WORKDIR /app
COPY --from=builder /app/outdir/. ./apps/${APP}/
WORKDIR /app/apps/${APP}
EXPOSE 3007
CMD ["node","dist/index.js"] 