FROM node:22 as base
RUN npm install -g pnpm turbo

FROM base AS prunner
ARG APP=http-server
WORKDIR /app
COPY . .
RUN turbo prune --scope=$APP --docker
FROM base AS installer
WORKDIR /app
ARG APP=http-server
COPY --from=prunner /app/out/json/ .
COPY --from=prunner /app/out/full/ .
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/${APP}/package.json ./apps/${APP}/package.json
RUN pnpm install --filter ${APP}


FROM base AS runner
ARG APP=http-server
WORKDIR /app
COPY --from=installer /app ./
WORKDIR /app/apps/${APP}
RUN pnpm --filter=${APP}... run build

EXPOSE 3002
CMD ["pnpm","run","dev"] 